# Generated by Django 2.2 on 2021-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openimis_url', models.CharField(max_length=200)),
                ('openhim_url', models.CharField(max_length=200)),
                ('mediator_url', models.CharField(max_length=200)),
                ('openhim_user', models.CharField(max_length=200)),
                ('openhim_passkey', models.CharField(max_length=200)),
                ('openimis_user', models.CharField(max_length=200)),
                ('openimis_passkey', models.CharField(max_length=200)),
                ('openimis_port', models.IntegerField()),
                ('openhim_port', models.IntegerField()),
                ('mediator_port', models.IntegerField()),
            ],
        ),
    ]
