# Generated by Django 2.2 on 2021-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='openimis_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
