# Generated by Django 2.2 on 2021-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20210406_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='mediator_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configs',
            name='openhim_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
