# Generated by Django 2.2 on 2021-04-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20210406_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configs',
            name='mediator_url',
        ),
    ]
