# Generated by Django 2.1.14 on 2021-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openimis_url', models.URLField()),
                ('openhim_url', models.URLField()),
                ('mediator_url', models.URLField()),
                ('openimis_port', models.IntegerField()),
                ('openhim_port', models.IntegerField()),
                ('mediator_port', models.IntegerField()),
            ],
        ),
    ]
