# Generated by Django 2.1.14 on 2021-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='mediator_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configs',
            name='openhim_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configs',
            name='openimis_url',
            field=models.CharField(max_length=200),
        ),
    ]
